#if defined _settings_included
  #endinput
#endif
#define _settings_included

#define TE_BEAMPOINTS 0
#define TE_BEAMENTPOINT 1
#define TE_KILLBEAM 99
#define DELTA_T 0.1		// seconds
#define BEAMLIFE 100		// deciseconds
#define MOVEACCELERATION 150	// units per second^2
#define REELSPEED 100		// units per second

#define SKILLS_PER_PAGE 7
#define SKILLO_PER_PAGE 6

#define BUTTON_DISTANCE 100
#define ADMIN_SETUP_BUTTON_BOX 20
